package marco.tumminia.capstone.codify.entities.annuncio;

public enum CategoriaAnnuncio {
	SVILUPPO_WEB, CONSULENZA, BUG_FIXING, SVILUPPO_DESKTOP, SVILUPPO_MOBILE, SVILUPPO_DI_GIOCO, SVILUPPO_DI_SISTEMI_INTEGRATI, SVILUPPO_APP_WEARABLE, SVILUPPO_AR_VR, SVILUPPO_BOT_ASSISTENTE_VIRTUALE

}
